### ISSUE TITLE
Bamboo.SesAdapter.RFC2822WithBcc.render_part throwing an error. 

### ISSUE THREAD

**Issue by Ivor** [kalys/bamboo_ses#10]
Hi

Just switched from using BambooSMTP to using BambooSES. We were using SMTP to connect to SES. 

When sending emails I am now getting this. 

09:34:47.788 [error] Task #PID<0.2197.0> started from #PID<0.2196.0> terminating ** 
(FunctionClauseError) no function clause matching in Mail.Encoders.QuotedPrintable.encode/3     
(mail) lib/mail/encoders/quoted_printable.ex:24: Mail.Encoders.QuotedPrintable.encode(nil, [], 0)     
(bamboo_ses) lib/bamboo/adapters/rfc2822_with_bcc.ex:59: Bamboo.SesAdapter.RFC2822WithBcc.render_part/2     (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2     
(elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2     
(bamboo_ses) lib/bamboo/adapters/rfc2822_with_bcc.ex:53: Bamboo.SesAdapter.RFC2822WithBcc.render_part/2     (bamboo_ses) lib/bamboo/adapters/ses_adapter.ex:37: Bamboo.SesAdapter.deliver/2     
(elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2     
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3 Function: #Function<0.73693256/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>     Args: []

I am currently lost as to what could be causing this issue. The emails "send" fine with the local adapter.

**Comment by kalys** [comment]
This will be fixed with PR https://github.com/kalys/bamboo_ses/pull/9

**Comment by Ivor** [comment]
Awesome! This is great news. Looking forward to the release. Thank you 👍

**Comment by Ivor** [comment]
For the moment I circumvented this issue by creating html templates for the emails as well. I was lucky that the emails are super simple. Sharing in case this helps someone else until the PR is merged.

**Comment by kalys** [comment]
0.1.4 is released

https://hex.pm/packages/bamboo_ses/0.1.4
