### ISSUE TITLE
Two DKIM signatures

### ISSUE THREAD

**Issue by Aleksandaar** [kalys/bamboo_ses#12]
Whenever I try to send an email using bamboo ses, seems like it is adding additional DKIM signature. 
I have one already set-up in Amazon SES - which will be sent, but there will alwasy be another signature for domain `amazonses.com`. #Can we somehow forbid adding this signature if it is being added in the `bamboo_ses` or `ex_aws`? #

**Comment by kalys** [comment]
Hello @Aleksandaar 

`bamboo_ses` doesn't have any logic on adding DKIM signature. I will investigate this within 3-5 days.
