### ISSUE TITLE
Support attachment Content-ID

### ISSUE THREAD

**Issue by rafaeliga** [kalys/bamboo_ses#18]
Hello,

I see that bamboo added support for content_id in attachment:

https://github.com/thoughtbot/bamboo/pull/475

I dont see it in the email sent by SES, is that something that need to be done in the adapter or in the Mail (https://github.com/DockYard/elixir-mail) itself?

Code:

`|> put_attachment("priv/mailer/header.jpg", content_id: "header")`

> --D5D9F6A9AB86E80A9E5253E2
Content-Type: image/jpeg
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=header.jpg

Thanks,

**Comment by kalys** [comment]
Hi,

Seems like https://github.com/DockYard/elixir-mail doesn't support it yet.

I'll investigate if I can create a PR there first on weekends.

**Comment by rafaeliga** [comment]
hey @kalys ,

Thanks for your fast answer!

I've added support for custom headers on elixir-mail, please take a look: https://github.com/DockYard/elixir-mail/pull/120

**Comment by rafaeliga** [comment]
@kalys quick update: its already on master now: https://github.com/DockYard/elixir-mail/commit/75a04c96138471b4fb90f554d2050794a8995690

**Comment by thiagomajesk** [comment]
Thanks for the nice work @rafaeliga!

**Comment by thiagomajesk** [comment]
Hi @kalys! Did you have a chance to take a look at @rafaeliga's PR yet? 
Is there anything that we can do to speed up the process and get this accepted?

Cheers!
