### ISSUE TITLE
Address encoding failure in 0.1.6

### ISSUE THREAD

**Issue by britton-jb** [kalys/bamboo_ses#24]
In 0.1.6 the `encode_address` [function](https://github.com/kalys/bamboo_ses/blob/master/lib/bamboo/adapters/ses_adapter.ex#L120-L123) fails to encode `"Example <noreply@example.com>"` where it's successfully handled in 0.1.5.

No patch incoming yet, but may be something I can address in the future.

**Comment by kalys** [comment]
Fixed in 0.1.8
