### ISSUE TITLE
Bump `ex_aws_ses` to 2.3

### ISSUE THREAD

**Issue by kreba** [kalys/bamboo_ses#44]
Thank you all for your work on this little but essential library!

The dependency `ex_aws_ses` was released to Hex in a new version **2.3.0**.
See https://github.com/ex-aws/ex_aws_ses/issues/18

The dependency declaration in `bamboo_ses` does not allow me to install that new version of `ex_aws_ses`. Please allow it.

(I've been using `ex_aws_ses` from master for a while now without any issues, so it should be safe.)

**Comment by kalys** [comment]
Fixed with v0.2.1

**Comment by kreba** [comment]
Thank you @kalys!
