### ISSUE TITLE
Add configuration options in README.md and module documetation

### ISSUE THREAD

**Issue by jfrolich** [kalys/bamboo_ses#5]

**Comment by kalys** [comment]
@jfrolich Thanks for the issue. I'll add description how to configure plugin within few days.

**Comment by jfrolich** [comment]
No worries, already managed to set it up, but would be better to have some documentation for new users. Thanks for building the library. Btw any reason you used send raw instead of the plain send?

**Comment by kalys** [comment]
@jfrolich You can send attachments only via SendRawEmail API.
